// GeoscientistToolkit/UI/TextViewer.cs

using System.Numerics;
using GeoscientistToolkit.Data.Text;
using GeoscientistToolkit.UI.Interfaces;
using GeoscientistToolkit.UI.Utils;
using GeoscientistToolkit.Util;
using ImGuiNET;

namespace GeoscientistToolkit.UI;

/// <summary>
/// Viewer and editor for text datasets
/// </summary>
public class TextViewer : IDatasetViewer
{
    private readonly TextDataset _dataset;
    private readonly ImGuiExportFileDialog _exportDialog;
    private string _editBuffer;
    private bool _hasUnsavedChanges;
    private bool _wordWrap = true;
    private float _fontSize = 13f;
    private bool _readOnly;
    private string _searchText = "";
    private int _searchResultIndex = -1;
    private List<int> _searchResults = new();

    public TextViewer(TextDataset dataset)
    {
        _dataset = dataset;
        _editBuffer = _dataset.Content ?? "";
        _readOnly = _dataset.IsGeneratedReport; // Generated reports start as read-only

        _exportDialog = new ImGuiExportFileDialog($"{_dataset.Name}_Export", "Export Text Document");
        _exportDialog.SetExtensions(
            (".txt", "Plain Text"),
            (".rtf", "Rich Text Format"));
    }

    public void DrawToolbarControls()
    {
        // Save button
        if (!_readOnly)
        {
            var saveDisabled = !_hasUnsavedChanges;
            if (saveDisabled)
            {
                ImGui.BeginDisabled();
            }

            if (ImGui.Button("Save"))
            {
                SaveChanges();
            }

            if (saveDisabled)
            {
                ImGui.EndDisabled();
            }

            if (_hasUnsavedChanges)
            {
                ImGui.SameLine();
                ImGui.TextColored(new Vector4(1, 0.7f, 0, 1), "* Unsaved changes");
            }

            ImGui.SameLine();
            ImGui.Separator();
        }

        // Read-only toggle
        ImGui.SameLine();
        if (ImGui.Checkbox("Read-only", ref _readOnly))
        {
            if (_readOnly && _hasUnsavedChanges)
            {
                // Ask user if they want to save before switching to read-only
                Logger.LogWarning("Switching to read-only mode with unsaved changes");
            }
        }

        ImGui.SameLine();
        ImGui.Separator();

        // Word wrap toggle
        ImGui.SameLine();
        ImGui.Checkbox("Word Wrap", ref _wordWrap);

        ImGui.SameLine();
        ImGui.Separator();

        // Font size
        ImGui.SameLine();
        ImGui.SetNextItemWidth(100);
        if (ImGui.SliderFloat("Font Size", ref _fontSize, 8f, 24f, "%.0f"))
        {
            _fontSize = Math.Clamp(_fontSize, 8f, 24f);
        }

        ImGui.SameLine();
        ImGui.Separator();

        // Search
        ImGui.SameLine();
        ImGui.SetNextItemWidth(200);
        if (ImGui.InputTextWithHint("##Search", "Search...", ref _searchText, 256, ImGuiInputTextFlags.EnterReturnsTrue))
        {
            PerformSearch();
        }

        ImGui.SameLine();
        if (ImGui.Button("Find"))
        {
            PerformSearch();
        }

        if (_searchResults.Count > 0)
        {
            ImGui.SameLine();
            ImGui.Text($"{_searchResults.Count} result(s)");

            ImGui.SameLine();
            if (ImGui.ArrowButton("PrevSearch", ImGuiDir.Left))
            {
                _searchResultIndex = (_searchResultIndex - 1 + _searchResults.Count) % _searchResults.Count;
            }

            ImGui.SameLine();
            if (ImGui.ArrowButton("NextSearch", ImGuiDir.Right))
            {
                _searchResultIndex = (_searchResultIndex + 1) % _searchResults.Count;
            }
        }

        ImGui.SameLine();
        ImGui.Separator();

        // Export button
        ImGui.SameLine();
        if (ImGui.Button("Export"))
        {
            _exportDialog.Open();
        }

        // Statistics
        ImGui.SameLine();
        ImGui.Separator();
        ImGui.SameLine();
        ImGui.Text($"Lines: {_dataset.LineCount} | Words: {_dataset.WordCount} | Chars: {_dataset.CharacterCount}");

        // Generated report info
        if (_dataset.IsGeneratedReport && !string.IsNullOrEmpty(_dataset.GeneratedBy))
        {
            ImGui.SameLine();
            ImGui.Separator();
            ImGui.SameLine();
            ImGui.TextColored(new Vector4(0.5f, 0.8f, 0.5f, 1.0f), $"Generated by: {_dataset.GeneratedBy}");
        }
    }

    public void DrawContent(ref float zoom, ref Vector2 pan)
    {
        var availableSize = ImGui.GetContentRegionAvail();

        // Handle export dialog
        _exportDialog.Submit();
        if (_exportDialog.IsFileSelected)
        {
            var exportPath = _exportDialog.GetSelectedFilePath();
            _dataset.Export(exportPath);
            _exportDialog.ClearSelection();
        }

        // Draw text editor
        var flags = ImGuiInputTextFlags.AllowTabInput;
        if (_readOnly)
        {
            flags |= ImGuiInputTextFlags.ReadOnly;
        }
        if (!_wordWrap)
        {
            flags |= ImGuiInputTextFlags.NoHorizontalScroll;
        }

        // Set font size by scaling
        var scale = _fontSize / ImGui.GetFontSize();
        ImGui.SetWindowFontScale(scale);

        if (ImGui.InputTextMultiline("##TextContent", ref _editBuffer, 1024 * 1024, availableSize, flags))
        {
            if (!_readOnly)
            {
                _hasUnsavedChanges = true;
                // Update statistics
                UpdateStatistics();
            }
        }

        // Reset font scale
        ImGui.SetWindowFontScale(1.0f);

        // Handle search highlighting (simplified - just show position)
        if (_searchResults.Count > 0 && _searchResultIndex >= 0 && _searchResultIndex < _searchResults.Count)
        {
            // In a full implementation, we would scroll to and highlight the search result
            // For now, we just show which result we're on
        }
    }

    public void Dispose()
    {
        if (_hasUnsavedChanges)
        {
            Logger.LogWarning("TextViewer disposed with unsaved changes");
        }
    }

    private void SaveChanges()
    {
        _dataset.Content = _editBuffer;
        _dataset.Save();
        _hasUnsavedChanges = false;
        UpdateStatistics();
        Logger.Log($"Saved changes to {_dataset.Name}");
    }

    private void UpdateStatistics()
    {
        _dataset.Content = _editBuffer;
        _dataset.CharacterCount = _editBuffer.Length;
        _dataset.LineCount = _editBuffer.Split('\n').Length;
        _dataset.WordCount = CountWords(_editBuffer);
    }

    private void PerformSearch()
    {
        _searchResults.Clear();
        _searchResultIndex = -1;

        if (string.IsNullOrEmpty(_searchText))
            return;

        var text = _editBuffer;
        var searchTerm = _searchText;
        var index = 0;

        while ((index = text.IndexOf(searchTerm, index, StringComparison.OrdinalIgnoreCase)) != -1)
        {
            _searchResults.Add(index);
            index += searchTerm.Length;
        }

        if (_searchResults.Count > 0)
        {
            _searchResultIndex = 0;
        }
    }

    private static int CountWords(string text)
    {
        if (string.IsNullOrWhiteSpace(text))
            return 0;

        var words = text.Split(new[] { ' ', '\t', '\n', '\r' }, StringSplitOptions.RemoveEmptyEntries);
        return words.Length;
    }
}
