// GAIA.GeoGenesis/Thermodynamics/ReactivePoreNetworkCoupling.cs
//
// Couples GeoGenesis aqueous chemistry to a PRISM pore-network model (the synthetic random PNM
// generated by the GeoGenesis reactor, or one built manually): mineral precipitation fills pore
// space (clogging / cementation / scale) and net dissolution reopens it. The evolved porosity,
// permeability and tortuosity — or simply their ratios to the initial state — can then be applied
// optionally by downstream flow tools: ReservoirFlux rock properties / mesh cells, the geothermal
// and aquifer PINN petrophysics, or CRAFT segments. Screening-grade closed forms, symmetric with
// the mechanical GeotechPoreNetworkCoupling:
//  - Porosity: φ = φ0 − v, with v the precipitated mineral volume per bulk rock volume
//    (v < 0 for net dissolution). Precipitation cannot fill more than the pore space.
//  - Permeability: Kozeny–Carman scaling k = k0·(φ/φ0)³·((1−φ0)/(1−φ))². Note this is plain KC
//    with no critical (percolation) porosity: the Verma & Pruess (1988) law used in
//    TOUGHREACT-class simulators adds a φc threshold below which k→0, so for strong cementation
//    localized at pore throats KC UNDER-estimates the permeability collapse — screening-grade.
//  - Tortuosity: Bruggeman-type τ = τ0·√(φ0/φ) — cement lengthens the remaining flow paths.
//  - Mean pore radius: r̄ = √(8kτ/φ) (equivalent Hagen–Poiseuille capillary bundle).
// Refs: Verma & Pruess (1988), J. Geophys. Res. 93; Steefel & Lasaga (1994); Xu et al. (2011),
// TOUGHREACT user guide (porosity-permeability laws for mineral scaling/clogging).

using System.Text.Json;

using GAIA.GeoGenesis.Materials;
using GAIA.GeoGenesis.Reactor;

namespace GAIA.GeoGenesis.Thermodynamics;

/// <summary>Pore-network petrophysical state evolved by chemistry (precipitation / dissolution).</summary>
/// <param name="PrecipitateVolumeFraction">Precipitated mineral volume per bulk rock volume driving this state (negative ⇒ net dissolution).</param>
/// <param name="FractureDamage">Overpressure fracture damage D ∈ [0,1] applied to this state (0 = intact rock).</param>
public readonly record struct ReactivePnmState(
    double Porosity,
    double Permeability_m2,
    double Tortuosity,
    double MeanPoreRadius_m,
    double PrecipitateVolumeFraction,
    double FractureDamage = 0.0);

public static class ReactivePoreNetworkCoupling
{
    /// <summary>Fallback grain density (kg/m³) when a mineral carries no density in the library.</summary>
    public const double DefaultMineralDensity_kg_m3 = 2700.0;

    // Overpressure fracturing constants, identical to the mechanical GeotechPoreNetworkCoupling:
    // microcrack porosity Δφ = 0.02·D, permeability enhancement 1 + D²·(10²−1) (the 1–2 decade jump
    // measured across brittle failure), and up to 40% tortuosity relief from through-going fractures.
    public const double CrackPorosityCoefficient = 0.02;
    public const double DamagePermeabilityFactor = 100.0;
    public const double CrackTortuosityRelief = 0.4;

    public static ReactivePnmState InitialState(PoreNetworkModel pnm) => new(
        pnm.Porosity, pnm.Permeability_m2, pnm.Tortuosity, pnm.MeanPoreRadius_m, 0.0);

    /// <summary>
    ///     Evolve φ/k/τ/r̄ for a precipitated (v &gt; 0) or net-dissolved (v &lt; 0) mineral volume
    ///     fraction of bulk rock. The identity state is returned for v = 0.
    /// </summary>
    public static ReactivePnmState Evolve(PoreNetworkModel pnm, double precipitateVolumeFraction)
        => Evolve(pnm, precipitateVolumeFraction, 0.0);

    /// <summary>
    ///     Evolve φ/k/τ/r̄ for a precipitated mineral volume fraction AND an overpressure fracture
    ///     damage D ∈ [0,1] (see <see cref="FractureDamage"/>): clogging closes the network while
    ///     fracturing reopens it — above the fracture pressure the damage term dominates and the
    ///     permeability jumps instead of declining.
    /// </summary>
    public static ReactivePnmState Evolve(PoreNetworkModel pnm, double precipitateVolumeFraction, double fractureDamage)
    {
        var phi0 = Math.Clamp(pnm.Porosity, 0.01, 0.95);
        var k0 = Math.Max(1e-24, pnm.Permeability_m2);
        var tau0 = Math.Max(1.0, pnm.Tortuosity);
        var damage = Math.Clamp(fractureDamage, 0.0, 1.0);

        var v = Math.Clamp(precipitateVolumeFraction, -0.5, phi0 * 0.999);
        var phiClog = Math.Clamp(phi0 - v, 1e-4, 0.95);
        var phi = Math.Clamp(phiClog + CrackPorosityCoefficient * damage, 1e-4, 0.95);

        var kClog = k0 * Math.Pow(phiClog / phi0, 3) * Math.Pow((1.0 - phi0) / Math.Max(1e-6, 1.0 - phiClog), 2);
        var k = kClog * (1.0 + damage * damage * (DamagePermeabilityFactor - 1.0));

        var tau = Math.Max(1.0, tau0 * Math.Sqrt(phi0 / phiClog) * (1.0 - CrackTortuosityRelief * damage));
        var radius = Math.Sqrt(8.0 * k * tau / phi);
        return new ReactivePnmState(phi, Math.Max(1e-24, k), tau, radius, v, damage);
    }

    /// <summary>
    ///     Overpressure fracture damage: 0 while the pore pressure stays below the fracture pressure
    ///     of the formation, then grows linearly with the overpressure and saturates at 1 (fully
    ///     fractured) when the pressure reaches twice the threshold. Screening-grade; the threshold
    ///     is the local fracture-gradient pressure (e.g. the PINN's fracture-pressure setting).
    /// </summary>
    public static double FractureDamageFromPressure(double pressure_bar, double fracturePressure_bar)
    {
        if (fracturePressure_bar <= 0 || !double.IsFinite(pressure_bar) || pressure_bar <= fracturePressure_bar)
            return 0.0;
        return Math.Clamp((pressure_bar - fracturePressure_bar) / fracturePressure_bar, 0.0, 1.0);
    }

    /// <summary>
    /// Overpressure fracture damage from Terzaghi effective stress. The rock fails in tension when the
    /// effective minimum horizontal stress σ' = σ_h,min − P_pore drops to −T (T = tensile strength),
    /// i.e. at pore pressure P = σ_h,min + T. Damage then grows with further overpressure and
    /// saturates at 1, reusing the <see cref="FractureDamageFromPressure"/> screening convention.
    /// Refs: Terzaghi (1943); Jaeger, Cook &amp; Zimmerman (2007), Fundamentals of Rock Mechanics.
    /// </summary>
    public static double FractureDamageFromEffectiveStress(double porePressure_bar, double minPrincipalStress_bar, double tensileStrength_bar)
    {
        if (minPrincipalStress_bar <= 0 || !double.IsFinite(porePressure_bar))
            return 0.0;
        var threshold = minPrincipalStress_bar + Math.Max(0.0, tensileStrength_bar);
        return FractureDamageFromPressure(porePressure_bar, threshold);
    }

    /// <summary>Density used to convert a precipitated mineral mass to volume (library value or default).</summary>
    public static double MineralDensity_kg_m3(CompoundLibrary library, string mineral)
    {
        var d = library.Find(mineral)?.Density_g_cm3;
        return d is > 0 ? d.Value * 1000.0 : DefaultMineralDensity_kg_m3;
    }

    /// <summary>Volume fraction of bulk rock occupied by the given precipitated masses (kg per mineral).</summary>
    public static double PrecipitateVolumeFraction(
        CompoundLibrary library, IReadOnlyDictionary<string, double> mineralMass_kg, double bulkVolume_m3)
    {
        if (bulkVolume_m3 <= 0) return 0.0;
        double volume = 0.0;
        foreach (var (mineral, kg) in mineralMass_kg)
            volume += kg / MineralDensity_kg_m3(library, mineral);
        return volume / bulkVolume_m3;
    }

    /// <summary>
    ///     Precipitate a supersaturated mineral toward equilibrium, removing its constituents from the
    ///     solution; returns mol of mineral removed per kg water. Shared by the geothermal and aquifer
    ///     couplers. <paramref name="extentScale"/> (0–1) multiplies the precipitated extent — used to
    ///     impose kinetic limits on slow silicates (see <see cref="MineralKinetics"/>); 1.0 = full
    ///     equilibrium.
    /// </summary>
    internal static double PrecipitateToEquilibrium(
        ThermodynamicState state, string mineral, double saturationIndex,
        CompoundLibrary library, ReactionGenerator generator, double extentScale = 1.0)
    {
        var compound = library.Find(mineral);
        if (compound == null || compound.Phase != CompoundPhase.Solid) return 0.0;
        var reaction = generator.GenerateSingleDissolutionReaction(compound);
        if (reaction == null) return 0.0;

        double maxExtent = double.MaxValue;
        foreach (var (species, coeff) in reaction.Stoichiometry)
        {
            if (coeff <= 0) continue;
            maxExtent = Math.Min(maxExtent, state.SpeciesMoles.GetValueOrDefault(species, 0.0) / coeff);
        }
        if (!double.IsFinite(maxExtent) || maxExtent <= 0) return 0.0;

        var relax = Math.Clamp(1.0 - Math.Pow(10.0, -saturationIndex), 0.0, 0.95);
        var scale = Math.Clamp(extentScale, 0.0, 1.0);
        var extent = relax * maxExtent * scale;
        foreach (var (species, coeff) in reaction.Stoichiometry)
        {
            if (coeff <= 0) continue;
            state.SpeciesMoles[species] = Math.Max(0.0, state.SpeciesMoles.GetValueOrDefault(species) - coeff * extent);
        }
        return extent;
    }

    /// <summary>
    ///     Read the pore network stored in a GeoGenesis reactor config (*.rxconfig.json). If the file
    ///     carries no explicit network, one is regenerated deterministically from its petrophysics
    ///     block and grid size — the same call the reactor itself uses.
    /// </summary>
    public static PoreNetworkModel LoadFromReactorConfig(string path)
    {
        var cfg = JsonSerializer.Deserialize<ReactorConfig>(File.ReadAllText(path))
                  ?? throw new InvalidDataException($"Could not read reactor config from '{path}'.");
        var petro = cfg.Petrophysics;
        return petro.SyntheticPoreNetwork ?? VirtualReactor.GenerateSyntheticPoreNetwork(
            petro.DefaultPorosity, petro.DefaultPermeability_m2, petro.DefaultTortuosity,
            Math.Max(1, cfg.Nx), Math.Max(1, cfg.Ny), Math.Max(1, cfg.Nz),
            petro.SyntheticPoreSeed, petro.ConnectedPoreFraction);
    }

    /// <summary>Reactor configs saved in a PRISM dataset (newest last), candidates for PNM import.</summary>
    public static IReadOnlyList<string> FindReactorConfigs(string datasetPath)
    {
        if (string.IsNullOrWhiteSpace(datasetPath)) return Array.Empty<string>();
        var dir = Path.Combine(datasetPath, "GeoGenesis", "reactor");
        if (!Directory.Exists(dir)) return Array.Empty<string>();
        return Directory.EnumerateFiles(dir, "*.rxconfig.json").OrderBy(File.GetLastWriteTimeUtc).ToList();
    }

    public static string Describe(PoreNetworkModel pnm) =>
        $"{pnm.ConnectedNodeCount:N0} connected + {pnm.DisconnectedNodeCount:N0} isolated pores, {pnm.ThroatCount:N0} throats, " +
        $"φ0 {pnm.Porosity:0.###}, k0 {pnm.Permeability_m2:E2} m², τ0 {pnm.Tortuosity:0.##}, r̄ {pnm.MeanPoreRadius_m:E2} m";
}
